#!/bin/bash

UID_ROOT=0
E_NOTROOT=67

if [ "$UID" -ne "$UID_ROOT" ]
then
	echo "Permission denied"
	echo "Failed install"
	exit $E_NOTROOT
fi


echo "|||---Installing dependencies---|||"
apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common curl -y

echo "|||---Adding repository key---|||"
curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

echo "|||---Installing repository---|||"
add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"

echo "|||---Installing sublime-text---|||"
apt install sublime-text -y

echo "|||---Installation has been succesfull!---|||"
